#%Module
setenv HEPMC3_DIR {{prefix}}
setenv HEPMC3DIR {{prefix}}
prepend-path PATH {{prefix}}/bin
prepend-path DYLD_LIBRARY_PATH {{prefix}}/lib
prepend-path LD_LIBRARY_PATH {{prefix}}/lib
prepend-path DYLD_LIBRARY_PATH {{prefix}}/lib64
prepend-path LD_LIBRARY_PATH {{prefix}}/lib64
prepend-path PYTHONPATH {{prefix}}/lib
prepend-path PYTHONPATH {{prefix}}/lib64
#prepend-path PYTHONPATH {{prefix}}/lib64/{{python_site_packages_subpath}}
