#%Module

setenv YASP_DIR {{yasp_dir}}
setenv YASP_PREFIX {{prefix}}
setenv YASP_EXEC {{yasp}}

prepend-path PATH {{prefix}}/bin
# prepend-path PYTHONPATH {{prefix}}/lib
prepend-path PYTHONPATH {{prefix}}/lib/{{python_site_packages_subpath}}
prepend-path LD_LIBRARY_PATH {{python_libdir}}
prepend-path DYLD_LIBRARY_PATH {{python_libdir}}

set-alias yasp_python {{python}}
set-alias yasp_cd "cd {{yasp_dir}}"
set-alias yaspenv "{{yasp_dir}}/yaspenv.sh"

# Saves Python header files on the path for compilation
prepend-path C_INCLUDE_PATH {{python_includedir}}
prepend-path CPLUS_INCLUDE_PATH {{python_includedir}}
