#%Module
setenv CPPYY_PATH {{prefix}}

prepend-path PATH {{prefix}}/bin

prepend-path PYTHONPATH {{prefix}}/lib/{{python_site_packages_subpath}} 
prepend-path PYTHONPATH {{prefix}}/lib64/{{python_site_packages_subpath}}
prepend-path DYLD_LIBRARY_PATH {{prefix}}/lib/{{python_site_packages_subpath}} 
prepend-path DYLD_LIBRARY_PATH {{prefix}}/lib64/{{python_site_packages_subpath}}
prepend-path LD_LIBRARY_PATH {{prefix}}/lib/{{python_site_packages_subpath}} 
prepend-path LD_LIBRARY_PATH {{prefix}}/lib64/{{python_site_packages_subpath}}

prepend-path PYTHONPATH {{prefix}}
prepend-path PYTHONPATH {{prefix}}
prepend-path DYLD_LIBRARY_PATH {{prefix}}
prepend-path DYLD_LIBRARY_PATH {{prefix}}
prepend-path LD_LIBRARY_PATH {{prefix}}
prepend-path LD_LIBRARY_PATH {{prefix}}

prepend-path PATH {{prefix}}/lib/{{python_site_packages_subpath}}/cppyy_backend/bin
prepend-path PYTHONPATH {{prefix}}/lib/{{python_site_packages_subpath}}/cppyy_backend/lib
prepend-path PYTHONPATH {{prefix}}/lib64/{{python_site_packages_subpath}}/cppyy_backend/lib
prepend-path DYLD_LIBRARY_PATH {{prefix}}/lib/{{python_site_packages_subpath}}/cppyy_backend/lib
prepend-path DYLD_LIBRARY_PATH {{prefix}}/lib64/{{python_site_packages_subpath}}/cppyy_backend/lib
prepend-path LD_LIBRARY_PATH {{prefix}}/lib/{{python_site_packages_subpath}}/cppyy_backend/lib
prepend-path LD_LIBRARY_PATH {{prefix}}/lib64/{{python_site_packages_subpath}}/cppyy_backend/lib

conflict root