#%Module
setenv HEPMC2_DIR {{prefix}}
setenv HEPMC2DIR {{prefix}}
setenv HEPMC2_VERSION 2.06.11
prepend-path PATH {{prefix}}/bin
prepend-path DYLD_LIBRARY_PATH {{prefix}}/lib
prepend-path LD_LIBRARY_PATH {{prefix}}/lib
prepend-path DYLD_LIBRARY_PATH {{prefix}}/lib64
prepend-path LD_LIBRARY_PATH {{prefix}}/lib64
prepend-path PYTHONPATH {{prefix}}/lib
prepend-path PYTHONPATH {{prefix}}/lib64
#prepend-path PYTHONPATH {{prefix}}/lib64/{{python_site_packages_subpath}}
