#%Module
setenv SHERPA_DIR {{prefix}}
setenv SHERPA_ROOT {{prefix}}
setenv SHERPA_SYS {{prefix}}
setenv SHERPADIR {{prefix}}
setenv SHERPAROOT {{prefix}}
setenv SHERPASYS {{prefix}}
prepend-path PATH {{prefix}}/bin
prepend-path DYLD_LIBRARY_PATH {{prefix}}/lib
prepend-path LD_LIBRARY_PATH {{prefix}}/lib
prepend-path LD_LIBRARY_PATH {{prefix}}/lib/SHERPA-MC
prepend-path PYTHONPATH {{prefix}}/lib

prepend-path PYTHONPATH {{prefix}}/lib/{{python_site_packages_subpath}} 
prepend-path PYTHONPATH {{prefix}}/lib64/{{python_site_packages_subpath}}
